### ISSUE TITLE
Error when using Repeater

### ISSUE THREAD

**Issue by teambound** [DNNCommunity/DNN.Events#140]
This was described in another post and was thought to be corrected in 7.01 but it has occurred. I am running dnn 8.00.4 and events 7.02

When I select repeater as the list type, I get this error

Error: Events is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: c:\inetpub\vhosts\rheebo.com\httpdocs\DesktopModules\Events\EventRpt.ascx(11): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) ---> System.Web.HttpCompileException: c:\inetpub\vhosts\rheebo.com\httpdocs\DesktopModules\Events\EventRpt.ascx(11): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath) at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate) at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath) at System.Web.UI.TemplateControl.LoadControl(String virtualPath) at DotNetNuke.Modules.Events.Events.LoadModuleControl() --- End of inner exception stack trace ---

**Comment by EPTamminga** [comment]
I tested this on my (current) version of Events704, and this works without problem.
I assume the new version that I have in the works, has this bug fixed.

**Comment by curioustoknow2019** [comment]
I am receiving a similar error after upgrading event module from 6.3.1 to 7.0.2 
I have also upgraded the platform from dnn 9.1.1 to 9.3.0

Error: Events is currently unavailable.DotNetNuke.Services.Exceptions.ModuleLoadException: c:\inetpub\wwwroot\Dnn\DesktopModules\Events\EventRpt.ascx(11): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) ---> System.Web.HttpCompileException: c:\inetpub\wwwroot\Dnn\DesktopModules\Events\EventRpt.ascx(11): error CS1061

**Comment by EPTamminga** [comment]
As mentioned, I am working on a version 7.0.4 (atm in fact), but I need some more time for bug fixing.

**Comment by curioustoknow2019** [comment]
so what should I do? is this  a known buy o 7.0.2? I see version 7.0.3
available but its only RC

**Comment by EPTamminga** [comment]
It is a known bug, 703 is an RC and will not be converted into a formal release.
If you have a test site, you can try to test 703 on your test site to see if it solves your problem.
Events 7.0.4 will upgrade both from 702 as well as 703

**Comment by curioustoknow2019** [comment]
When 7.0.4 will be released ?

**Comment by curioustoknow2019** [comment]
Do you know when 7.0.4 will be released ?

What’s the better way to revert back to 6.3.1 my last working dnn event module without having to roll back dnn evoq platform from 9.3.0 to 9.1.1?

**Comment by EPTamminga** [comment]
@curioustoknow2019 
As mentioned, I am working on a version 7.0.4 (atm in fact), but I need some more time for bug fixing.
If you have a local (copy) test site, I could mail you an alpha/test version for verification, I hope to have a test version next week.

I am not sure if Events 6.3.1 will work on DNN 9.3.x

Please, remember that DNN = work of volunteers...

**Comment by curioustoknow2019** [comment]
we can see calendar displayed. but for some reasons v7.0.2 is not saving list view  and it is throwing that error. 

https://imgur.com/tpg2Ct7
https://imgur.com/7fZ9rdL
https://imgur.com/YpyTSdM
https://imgur.com/69cTamM

**Comment by curioustoknow2019** [comment]
I updated to 7.0.3 RC and the error is gone.
