### ISSUE TITLE
dnn event upgrade from 6.3.1 to 7.0.2  issue

### ISSUE THREAD

**Issue by curioustoknow2019** [DNNCommunity/DNN.Events#183]
I am receiving this error after upgrading event module from 6.3.1 to 7.0.2
I have also upgraded the platform from dnn 9.1.1 to 9.3.0

Error: Events is currently unavailable.DotNetNuke.Services.Exceptions.ModuleLoadException: c:\inetpub\wwwroot\Dnn\DesktopModules\Events\EventRpt.ascx(11): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) ---> System.Web.HttpCompileException: c:\inetpub\wwwroot\Dnn\DesktopModules\Events\EventRpt.ascx(11): error CS1061

**Comment by curioustoknow2019** [comment]
I am receiving this error after upgrading event module from 6.3.1 to 7.0.2
I have also upgraded the platform from dnn 9.1.1 to 9.3.0

Error: Events is currently unavailable.DotNetNuke.Services.Exceptions.ModuleLoadException: c:\inetpub\wwwroot\Dnn\DesktopModules\Events\EventRpt.ascx(11): error CS1061: 'ASP.desktopmodules_events_eventrpt_ascx' does not contain a definition for 'SelectCategory_CategorySelected' and no extension method 'SelectCategory_CategorySelected' accepting a first argument of type 'ASP.desktopmodules_events_eventrpt_ascx' could be found (are you missing a using directive or an assembly reference?) ---> System.Web.HttpCompileException: c:\inetpub\wwwroot\Dnn\DesktopModules\Events\EventRpt.ascx(11): error CS1061

**Comment by curioustoknow2019** [comment]
updated to 7.0.3 and that fixed the error

**Comment by curioustoknow2019** [comment]
updated to 7.0.3 and that fixed the error
